server:
  port: 8081

spring:

  kafka:
    bootstrap-servers: ${KAFKA_SERVER}

    # Configurações globais para consumidores
    consumer:
      auto-offset-reset: earliest

    # Configurações específicas para o consumer de processamento de vídeos
    video-consumer:
      group-id: video-group
      topic: video-topic

    # Configurações específicas para o consumer de notificações por e-mail
    email-consumer:
      group-id: email-notification-group
      topic: v1.video-upload-status

    # Configurações do producer (se necessário)
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer


  # Configurações do serviço de e-mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: matheuspatricio999@gmail.com
    password: gnhf vmpj yqva opyt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}

video:
  service:
    url: ${VIDEO_SERVICE_URL}
    keycloak-url: ${KEYCLOAK_URL}
    keycloak-realm: master
    keycloak-client-id: tech-challenge-payments
    keycloak-client-secret: "**********"