apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mensageria-hackaton-hpa
  namespace: default-namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mensageria-hackaton-deployment
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80