apiVersion: apps/v1
kind: Deployment
metadata:
  name: mensageria-hackaton-deployment
  namespace: default-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mensageria-hackaton
  template:
    metadata:
      labels:
        app: mensageria-hackaton
    spec:
      containers:
        - name: mensageria-hackaton
          image: matheuspatricio0/mensageria-hackaton:latest
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8081
          env:
            - name: KAFKA_SERVER
              valueFrom:
                secretKeyRef:
                  name: mensageria-env-secrets
                  key: KAFKA_SERVER
            - name: KEYCLOAK_URL
              valueFrom:
                secretKeyRef:
                  name: mensageria-env-secrets
                  key: KEYCLOAK_URL
            - name: VIDEO_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: mensageria-env-secrets
                  key: VIDEO_SERVICE_URL
            - name: ISSUER_URI
              valueFrom:
                secretKeyRef:
                  name: mensageria-env-secrets
                  key: ISSUER_URI
            - name: SPRING_MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mensageria-env-secrets
                  key: SPRING_MAIL_USERNAME
            - name: SPRING_MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mensageria-env-secrets
                  key: SPRING_MAIL_PASSWORD
