apiVersion: v1
kind: Service
metadata:
  name: mensageria-service
  namespace: default-namespace
spec:
  selector:
    app: mensageria-hackaton
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: LoadBalancer